feat(project form): creating a new project with an existing short code (DEV-3204)
dasch-swiss/dsp-das pull request #1368
Opened 2024-01-22 12:31 UTC by domsteinbach

resolves DEV-3204

2024-01-22 13:39 UTC, irmastnt requested changes

2024-01-22 13:39 UTC, irmastnt commented on apps/dsp-app/src/app/project/reusable-project-form/reusable-project-form.component.ts
> +function shortcodeExistsValidator(shortcodes$: Observable<string[]>): AsyncValidatorFn {
create validator class like this:
```
export class ShortCodeExistsValidator extends Validators {
    static createValidator(shortcodes: string[]): AsyncValidatorFn {
```

2024-01-22 13:39 UTC, irmastnt commented on apps/dsp-app/src/app/project/reusable-project-form/reusable-project-form.component.ts
> +        [shortcodeExistsValidator(this.shortcodes$)],
**use dynamic validation:** 
```

dynamicValidation: {
                    shortcodes: {
                        async: [ShortcodeExistsValidator.createValidator(this.shortcodes$)],
                    },
                },
```

2024-01-22 13:40 UTC, domsteinbach commented on apps/dsp-app/src/app/project/create-project-form-page/create-project-form-page.component.ts
> +        (error: ApiResponseError) => {
There was a bad request error from the Api, but there was no error thrown nor anything displayed. Therefore the loader spinned forever. If there is a general error handler, it does not handle what's needed in that case. I'll be glad to remove it though.

2024-01-23 13:37 UTC, irmastnt approved these changes

2024-01-24 07:47 UTC, derschnee68 approved these changes

2024-01-24 08:12 UTC, merged