feat: assigns new project to the current user automatically, if creat…(DEV-3658)
dasch-swiss/dsp-das pull request #1600
Opened 2024-05-17 11:05 UTC by irmastnt

feat: assigns new project to the current user automatically, if created from my projects (DEV-3658)

2024-05-17 12:01 UTC, derschnee68 commented
I don't think adding a new route for creating a project from user is a good idea.
Shouldn't the creator of a project be assigned as the project member by default ?

2024-05-17 12:04 UTC, irmastnt commented
> I don't think adding a new route for creating a project from user is a good idea. Shouldn't the creator of a project be assigned as the project member by default ?

Project may be created for other members as well. Or without members at all.

2024-05-17 12:22 UTC, derschnee68 requested changes

2024-05-17 12:22 UTC, derschnee68 commented on apps/dsp-app/src/app/project/create-project-form-page/create-project-form-page.component.ts
> +          if (this._router.url.includes(RouteConstants.assignCurrentUser)) {
dont use a map, use a tap or better, add this in subscription

2024-05-21 13:59 UTC, derschnee68 approved these changes

2024-05-21 13:59 UTC, merged