refactor(add user form): remove validation and error msgs
dasch-swiss/dsp-das pull request #1675
Opened 2024-07-01 14:45 UTC by domsteinbach

resolves DEV-3337

2024-07-01 15:22 UTC, irmastnt requested changes
We are adding language translations to all new code from the last week.

2024-07-01 15:27 UTC, domsteinbach commented
> We are adding language translations to all new code from the last week.

Good to know, but what does that imply? This code is from now and not last week. Is there any inconvenience for adding/changing translations? What are the changes requested?

2024-07-02 07:46 UTC, domsteinbach commented
The translations are introduced.

2024-07-02 07:56 UTC, irmastnt commented on apps/dsp-app/src/app/project/collaboration/add-user/add-user.component.html
>            <mat-form-field class="large-field select-user">
mat-label is missing

2024-07-02 07:57 UTC, irmastnt approved these changes

2024-07-02 08:36 UTC, domsteinbach commented on apps/dsp-app/src/app/project/collaboration/add-user/add-user.component.ts
> +  selectUserForm: FormGroup;
Here not. ts allowes class props to be declared without initialisation as long they are initialised before any usage. As ngOnInit is guaranteed to run before any component methods that rely on selectUserForm, it is safe to initialize the form there and there is no complain.

Here it is better without an assertion as if there are any changes in the business logic an error is thrown if it breaks. If we use "?" or "!" there will be no complain but maybe a bug.
In general we should not use "?" or "!" if there is really no other way. In most of the cases where an assertion is used, the component is not made nicely imho.

2024-07-02 08:38 UTC, domsteinbach commented on apps/dsp-app/src/app/project/collaboration/add-user/add-user.component.ts
> +      addUser: new FormControl<ReadUser | null>(null),
I prefer the more verbose (for me) here :-)

2024-07-02 08:40 UTC, merged