Feature/dev 2468 improve paging of search results
dasch-swiss/dsp-das pull request #1995
Opened 2024-12-10 09:14 UTC by domsteinbach

resolves DEV-2468

2025-01-15 11:47 UTC, derschnee68 requested changes
I would like to talk about it with everybody to think about using a lib to do this

2025-01-22 09:34 UTC, derschnee68 requested changes

2025-01-22 09:34 UTC, derschnee68 commented on libs/vre/resource-editor/resource-properties/src/lib/properties-display.component.ts
> +      <dasch-swiss-app-incoming-resource-pager
dasch-swiss-app-incoming-resource-pager

why don't you call it app-incoming-resource-pager ? or dasch-swiss-incoming-resource-pager?

2025-01-22 09:34 UTC, derschnee68 commented on libs/vre/resource-editor/resource-properties/src/lib/properties-display.component.ts
> +  pagerComponent: IncomingResourcePagerComponent | undefined;
I think you could say that it IS defined (remove undefined), right ?

2025-01-22 09:34 UTC, derschnee68 commented on libs/vre/ui/ui/src/lib/incoming-resource-pager/incoming-resource-pager.component.ts
> +  turnPage(dir: 1 | -1) {
changePage rather than turnPage ?

2025-01-22 09:34 UTC, derschnee68 commented on libs/vre/pages/ontology/ontology-classes/src/lib/list-view/list-view.component.html
> +  <dasch-swiss-app-pager (pageIndexChanged)="doSearch($event)" [numberOfAllResults]="numberOfAllResults">
use the one tag version <dasch-swiss-app-pager />

2025-01-22 09:34 UTC, derschnee68 commented on libs/vre/pages/ontology/ontology-classes/src/lib/list-view/list-view.component.html
> +  <dasch-swiss-app-pager (pageIndexChanged)="doSearch($event)" [numberOfAllResults]="numberOfAllResults">
<dasch-swiss-app-pager />

Also why not call it dasch-swiss-pager

2025-01-27 08:52 UTC, domsteinbach commented on libs/vre/resource-editor/resource-properties/src/lib/properties-display.component.ts
> +      <dasch-swiss-app-incoming-resource-pager
Because I only added the "incoming-resource" to be more precise. The "dasch-swiss" was once the convention and I simply kept it.

2025-01-27 09:10 UTC, domsteinbach commented on libs/vre/resource-editor/resource-properties/src/lib/properties-display.component.ts
> +  pagerComponent: IncomingResourcePagerComponent | undefined;
Maybe, that component was not of my concern.

2025-01-27 09:15 UTC, domsteinbach commented on libs/vre/ui/ui/src/lib/incoming-resource-pager/incoming-resource-pager.component.ts
> +  turnPage(dir: 1 | -1) {
Agree.

2025-01-27 10:05 UTC, derschnee68 approved these changes

2025-01-27 10:06 UTC, merged